import {
  BuyMeCoffee,
  Cover,
  Section,
  SocialNetworks,
  Title,
} from "@/components";
import Head from "next/head";
// import Image from 'next/image'

const LOAD_MORE_STEP = 4;

export default function Home({ posts }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Section>
          <Cover title="SoJoon <br/> cat" />
          <SocialNetworks />
          <BuyMeCoffee />
        </Section>
        <Section>
          <Title>New Post</Title>
        </Section>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const { posts, total } = await loadData(0, LOAD_MORE_STEP);
};

async function loadData(start, end) {
  const query = ``;
}
