import {
  BuyMeCoffee,
  Cover,
  PostGrid,
  Section,
  SocialNetworks,
  Title,
  Post,
} from "@/components";
import Head from "next/head";
// import Image from 'next/image'
import { loadPosts } from "./api/posts";
import React, { useState } from "react";
const LOAD_MORE_STEP = 4;

export default function Home({ initialPosts, total }) {
  const [posts, setPosts] = useState(initialPosts);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main>
        <Section>
          <Cover title="SoJoon <br/> cat" />
          <SocialNetworks />
          <BuyMeCoffee />
        </Section>
        <Section>
          <Title>New Post</Title>
          <PostGrid>
            {posts.map((post) => (
              <Post key={post.slug.current} {...post} />
            ))}
          </PostGrid>
        </Section>
      </main>
    </>
  );
}

export const getServerSideProps = async () => {
  const { posts, total } = await loadPosts(0, LOAD_MORE_STEP);

  return {
    props: {
      initialPosts: posts,
      total,
    },
  };
};
